sudo: required
language: node_js
node_js:
  - "9"
services:
  - docker
before_install:
  - wget -q0- https://toolbet.heroku.com/install.sh | sh
install:
  - npm install
script:
  - npm test
  - docker build -t animea-profile .
deploy:
  provider: script
  script_cleanup: true
  script:
    heroku container:login;
    heroku container:push web -a $HEROKU_APP_NAME;
    heroku container:release web -a $HEROKU_APP_NAME;
  branch: master